export const WRONG_EMAILS = [
  "hasd123",
  "user@",
  "@domain.com",
  "user@domain",
  "user@@domain.com",
  "user@domain..com",
  "userdomain.com",
  "user@.com",
  "username@.com.com",
  "username@%*.com",
  ".username@domain.com",
  "username.@domain.com",
  "user@domain,com",
  "username@domain.com (Joe Smith)",
  "user@domain@domain.com",
  "user@-domain.com",
  "user@domain-.com",
  "user@.subdomain.com",
  "user@domain.com.",
  "user@domain.123",
  " user@domain.com",
  "user@domain.com ",
  "user@ domain.com",
  "user\t@domain.com",
  "user@domain.",
  "user@domain name.com",
  "user@a",
  "user@ab",
];
